name: Hello World

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! ${GITHUB_REF#refs/tags/}"
